# Generated by Django 3.0.4 on 2021-07-04 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id_consult', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='maladies',
            fields=[
                ('id_maladie', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lib_malade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='medicaments',
            fields=[
                ('code_med', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code_barre_med', models.CharField(max_length=18)),
                ('lib_med', models.CharField(max_length=100)),
                ('maladies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.maladies')),
            ],
        ),
        migrations.CreateModel(
            name='money',
            fields=[
                ('id_money', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lib_money', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='organism_assur',
            fields=[
                ('id_organism', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lib_organism', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('fixe', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('m', 'masculain'), ('f', 'féminin')], max_length=1)),
                ('adresse', models.CharField(max_length=60)),
                ('date_naiss', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='payment_methode',
            fields=[
                ('id_methode', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lib_methode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pays',
            fields=[
                ('code_pays', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nom_pays', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='visiteur',
            fields=[
                ('id_v', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('1', 'Patient'), ('2', 'Autre')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='rendez_vous',
            fields=[
                ('id_rdv', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(unique=True)),
                ('etat_rdv', models.CharField(choices=[('1', 'malade'), ('2', 'autre visite')], max_length=1)),
                ('canceled', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cout', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.consultation')),
                ('id_methode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.payment_methode')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='code_pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.pays'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ordannance',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('maladies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.maladies')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='medicaments_ord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.medicaments')),
                ('id_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.ordannance')),
            ],
        ),
        migrations.CreateModel(
            name='intervention_ch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.maladies')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='historique_maladie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.maladies')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.rendez_vous'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient'),
        ),
        migrations.CreateModel(
            name='certif',
            fields=[
                ('id_certif', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=0)),
                ('datedeb', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.CharField(max_length=1450)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='assuranc',
            fields=[
                ('id_assurance', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.organism_assur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
    ]
