# Generated by Django 3.0.4 on 2021-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20210705_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='date',
            field=models.DateTimeField(default='0001-00-00 00:00:00', unique=True),
        ),
    ]
